function draw_game()
    cls(0)
    draw_stars()
    draw_player()
    draw_blast()
    draw_score()
    draw_bullets()
    draw_enemies()
    draw_explosions()
    draw_shock_waves()
    draw_particules()
    draw_debug()
end